language: c
git:
  depth: false
services:
- docker
jobs:
  include:
  - stage: build
    script:
    - set -e
    - rm -rf build
    - "./cicd/run build"
    - "./cicd/run test"
    - "./cicd/run pack"
  fast_finish: true
deploy:
  provider: releases
  api_key:
    # github: Settings -> Developer settings -> Personal access tokens -> Generate new token
    # in repo root: travis login ; travis encrypt <github token>
    secure: "T/qIv0FfvSbUu2OLpV+TyRDrQy5t2CVdCJmHjh28PgGvxmr74+XPEo1B89lI+EdE0BKibhn4rfbfFP8A4i4VNbShQz2XehyDCfHzP2EpbzqKWGkWs1vIfesyV7vYU7R3iro95gbbLQM/kZfTw4oVlLQiz6ZE55ULbrOrx9fAcYC/+2LpC+oGBb6c/hFHFsaVTDZEGADkseRHxEc1oN1RXoxOwJhLkYGBrQTzmcKJNvYnnQ4qNNE70aPugrEJUyFE0aCkfg2QNWJuUlMRV4ldoVe4nRFmaOyPSS/Webbyi/iOkXRpCgL5Lo3DJ0mEu904fHXmT1Syn/oKibYTT2BfRy22o+FVDcnD9bIYFDyP4q/iWEDXp3Phlt7vV2vq4v2aAj9yT/hXjgb66Qk7+TkgPT1TKoo51L9JEWaJs6MTacg6iI7lub0kreyBsn4s/x8s+3w6sZ7BQpgu5CNUfEdECF2KwMJqF8HmFFj+MsnNGPVYNqzYMlqDLcURCfh59YHvbyKfcTAAt6yWZmeMy0NLwawWmItOYG6f+CY2Tif7lYl5YZkDeCKGIS8sH/uoua7FwZ3CmgEdrFIqhf1XWmuVxjcAabsZ1sDV91x4KQyCWcfuXawPGUUJXtKotN8gVbo3A4LgYmPMSx6cCTIpFRNzzqQLAl1y6vNn4CnPhElKRQs="
  file_glob: true
  file: build/assets/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
